version: '3'

services:
#  demo-frontend:
#    extends:
#      file: docker-compose.base.yml
#      service: nx-app-base
#    command: npm run demo-frontend:dev:docker
#    ports:
#      - "4200:4200"

  demo-frontend2:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run demo-frontend2:dev:docker
    ports:
      - "4200:4200"

  demo-backend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run demo-backend:dev:docker
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=bdung
    depends_on:
      - mongo

  mongo:
    ports:
      - '27017:27017'
    container_name: vcnft-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    container_name: postgres
#    volumes:
#      - vcnft-postgres:/var/lib/postgresql/data
#    ports:
#      - '5433:5432'
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - vcnft-redis:/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "3002:3002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-frontend2
      - demo-backend

#  ngrok:
#    image: ngrok/ngrok:latest
#    restart: unless-stopped
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - 4040:4040
#    depends_on:
#      - nginx

#volumes:
#  vcnft-redis:
#    driver: local
#  vcnft-postgres:


networks:
  default:
    driver: bridge
