version: '3'

services:

  demo-frontend2:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run demo-frontend2:dev:docker
    ports:
      - "4200:4200"

  demo-backend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run demo-backend:dev:docker
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=bdung
    depends_on:
      - mongo

  mongo:
    ports:
      - '27017:27017'
    container_name: vcnft-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    image: mongo
    volumes:
      - vcnft-mongo:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
    depends_on:
      - demo-frontend2
      - demo-backend

volumes:
  vcnft-mongo:

networks:
  default:
    driver: bridge
