import './globals.css'
import type { Metadata } from 'next'
import { Space_Grotesk, Roboto } from 'next/font/google'

const grotesk = Space_Grotesk({ subsets: ['latin'] })
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className + " min-h-screen"}>{children}</body>
    </html>
  )
}
